CRITICAL - 2021-12-19 20:27:06 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1700): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): CodeIgniter\Model->__call('getData', Array)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-19 20:31:12 --> Too few arguments to function App\Models\M_login::cek_login_v2(), 0 passed in C:\xampp\htdocs\cro4\app\Controllers\C_login.php on line 53 and exactly 2 expected
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 20:31:34 --> Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#3 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 20:32:36 --> Call to undefined function CodeIgniter\Database\Postgre\pg_pconnect()
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#3 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 20:35:22 --> pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 20:35:26 --> pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 20:38:05 --> pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 20:41:05 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 20:41:11 --> pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 20:51:55 --> Class '\CodeIgniter\Database\PostgreSQL\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(336): CodeIgniter\Database\Config::connect('db3')
#2 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(43): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-19 20:52:10 --> Class '\CodeIgniter\Database\pgsql\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(336): CodeIgniter\Database\Config::connect('db3')
#2 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(43): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-19 20:52:18 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 20:59:47 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 21:00:27 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 21:01:06 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 21:04:41 --> pg_connect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_connect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1819): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\cro4\app\Models\M_login.php(56): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(53): App\Models\M_login->cek_login_v2()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#9 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-19 21:24:07 --> pg_pconnect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:29:56 --> pg_pconnect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:30:36 --> pg_pconnect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:31:54 --> pg_pconnect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:32:57 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:34:25 --> pg_pconnect(): Unable to connect to PostgreSQL server: invalid connection option &quot;username&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:34:57 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:40:35 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:40:40 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:41:40 --> pg_pconnect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:41:52 --> pg_pconnect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:42:03 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:44:20 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:44:22 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:44:32 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:44:32 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:44:36 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('host=192.168.50...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:44:48 --> pg_pconnect(): Unable to connect to PostgreSQL server: received invalid response to SSL negotiation: Y
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('port=3306 user=...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:45:21 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;Aji Syahputra&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('password=--pass...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:45:41 --> pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;ssm&quot;
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('user=ssm passwo...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 21:49:20 --> Cannot redeclare App\Models\M_login::cek_login_v2()
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-19 21:49:43 --> Call to undefined method CodeIgniter\Database\Postgre\Connection::where()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 21:50:10 --> Call to undefined method CodeIgniter\Database\Postgre\Connection::getWhere()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 21:50:38 --> Call to undefined method CodeIgniter\Database\Postgre\Connection::getWhere()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 21:53:39 --> Call to a member function num_rows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 21:54:56 --> Call to a member function getNumRows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 21:55:35 --> Call to a member function getNumRows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 21:56:11 --> Call to undefined method CodeIgniter\Database\Postgre\Result::getNumRows()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 21:57:23 --> Call to undefined method CodeIgniter\Database\Postgre\Connection::last_query()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 21:58:10 --> Call to a member function getNumRows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 21:58:55 --> Call to undefined method CodeIgniter\Database\Postgre\Result::countResultAll()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 21:59:18 --> Call to undefined method CodeIgniter\Database\Postgre\Result::countAll()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:00:27 --> Call to undefined method CodeIgniter\Database\Postgre\Result::get()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:00:59 --> Call to a member function getRow() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:01:21 --> Call to a member function get() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:01:50 --> Call to a member function getResult() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:02:05 --> Call to a member function numRows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:02:16 --> Call to a member function num_rows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:04:05 --> Call to undefined method CodeIgniter\Database\Postgre\Result::getNumRows()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:04:49 --> Call to a member function getNumRows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:04:59 --> Call to a member function num_rows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:05:34 --> Call to undefined method CodeIgniter\Database\Postgre\Result::countResultAll()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:05:52 --> Call to undefined method CodeIgniter\Database\Postgre\Result::countAllResults()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:06:10 --> Call to undefined method CodeIgniter\Database\Postgre\Result::countAll()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:09:40 --> Call to undefined method CodeIgniter\Database\Postgre\Result::getRowCount()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:10:05 --> Call to undefined method CodeIgniter\Database\Postgre\Result::getNumRows()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:14:31 --> Call to undefined method CodeIgniter\Database\Postgre\Result::countAll()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:17:11 --> Call to a member function getNumRows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:17:30 --> Call to a member function numrows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:17:46 --> Call to a member function numRows() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:20:00 --> pg_query(): Query failed: ERROR:  syntax error at or near &quot;FROM&quot;
LINE 1: SELECT COUNT* FROM erpuser WHERE username='aji' AND userpass...
                      ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 194, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(194): pg_query(Resource id #103, 'SELECT COUNT* F...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\Postgre\Connection->execute('SELECT COUNT* F...')
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT* F...')
#4 C:\xampp\htdocs\cro4\app\Models\M_login.php(48): CodeIgniter\Database\BaseConnection->query('SELECT COUNT* F...')
#5 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-12-19 22:21:19 --> Call to a member function getRowArray() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:23:44 --> pg_pconnect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('user=ssm passwo...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Models\M_login.php(48): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(us...')
#5 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'ssm1234')
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-12-19 22:23:55 --> Unable to connect to the database.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\cro4\app\Models\M_login.php(48): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(us...')
#2 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-19 22:23:58 --> Unable to connect to the database.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\cro4\app\Models\M_login.php(48): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(us...')
#2 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-19 22:24:33 --> pg_pconnect(): Unable to connect to PostgreSQL server: could not connect to server: Software caused connection abort (0x00002745/10053)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('user=ssm passwo...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Models\M_login.php(48): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(us...')
#5 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-12-19 22:24:58 --> pg_pconnect(): Unable to connect to PostgreSQL server: could not connect to server: Software caused connection abort (0x00002745/10053)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('user=ssm passwo...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(33): CodeIgniter\Database\BaseConnection->query('select username...')
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->tes_db3()
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-19 22:28:09 --> pg_pconnect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('user=ssm passwo...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Models\M_login.php(48): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(us...')
#5 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-12-19 22:28:50 --> pg_pconnect(): Unable to connect to PostgreSQL server: could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host &quot;192.168.50.2&quot; and accepting
	TCP/IP connections on port 5432?
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(98): pg_pconnect('user=ssm passwo...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(377): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\cro4\app\Models\M_login.php(48): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(us...')
#5 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-12-19 22:34:26 --> Call to undefined method CodeIgniter\Database\Postgre\Result::countAllResults()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:38:22 --> Call to undefined method stdClass::Count()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(66): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:45:13 --> Call to a member function getRow() on array
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-19 22:47:17 --> Use of undefined constant iduser - assumed 'iduser' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(76): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 76, Array)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-19 22:50:25 --> Call to a member function set_userdata() on null
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#4 {main}
